POST  http://localhost:8000/api/register
Content-Type: "application/json"

{
    "name": "CJ Colmeia",
    "email": "cjcearense@gmail.com",
    "telephone": "123456789",
    "type": "driver",
    "password": "12345678",
    "brand": "Ford",
    "model": "Fiesta",
    "year": 2020,
    "plate": "ABC1234",
}