POST  http://localhost:8000/api/register
Content-Type: "application/json"

{
    "name": "CJ Colmeia",
    "email": "cjdabahia@gmail.com",
    "telephone": "123456789",
    "type": "driver",
    "password": "12345678"
}